@startuml
rectangle {
    actor "Skeleton" as S
    rectangle "gd : GameDirector" as gd
    rectangle "rn : RoadNetwork" as rn
    rectangle "cr1 : Crossing" as cr1
    rectangle "cr2 : Crossing" as cr2
    rectangle "r1 : Road" as r1
    rectangle "r2 : Road" as r2
    rectangle "l1 : Lane" as l1
    rectangle "l2 : Lane" as l2
    rectangle "l3 : Lane" as l3
    rectangle "sc1 : SurfaceCondition" as sc1
    rectangle "sc2 : SurfaceCondition" as sc2
    rectangle "sc3 : SurfaceCondition" as sc3
    rectangle "c : Cleaner" as c
    rectangle "bd : BusDriver" as bd
    rectangle "s : SnowPlower" as sp
    rectangle "b : Bus" as b
    rectangle "h : SweeperHead" as sh
    rectangle "c1: Car" as c1
    rectangle "c2: Car" as c2
    rectangle "t: Timer" as t
    rectangle "e: Economy" as e

    S -right-> gd : 1: <<create>>
    gd --> rn : 1.1: <<create>>
    gd --> c : 1.2: <<create>>
    gd --> bd : 1.3: <<create>>
    gd --> c1 : 1.4: <<creaete>>
    gd --> c2 : 1.5: <<creaete>>
    gd --> t : 1.6: <<create>>
    gd --> e : 1.7: <<create>>
    rn --> cr1: 1.1.1: <<create>>
    rn --> cr2: 1.1.2: <<create>>
    rn --> r1: 1.1.3: <<create>>
    rn --> r2: 1.1.4: <<create>>
    r1 --> l1: 1.1.3.1: <<create>>
    r1 --> l2: 1.1.3.2: <<create>>
    r2 --> l3: 1.1.4.1: <<create>>
    l1 --> sc1: 1.1.3.1.1: <<create>>
    l2 --> sc2: 1.1.3.2.1: <<create>>
    l3 --> sc3: 1.1.4.1.1: <<create>>
    c --> sp: 1.2.1: <<create>>
    sp --> sh: 1.2.1.1: <<create>>
    bd --> b : 1.3.1: <<create>>
    
}
@enduml