@startuml
rectangle {
left to right direction

:Cleaner: --|> :Player: 
:BusDriver: --|> :Player:

rectangle "Choosing the lane in a crossing" {
    (Choosing the lane) as usecase1
}

Player -- usecase1

}
@enduml