@startuml
rectangle {
left to right direction

:Cleaner: --|> :Player: 
:BusDriver: --|> :Player:

rectangle "Changing the lane" {
    (Changing the lane) as usecase1
}

Player --> usecase1

}
@enduml