@startuml
rectangle {
left to right direction

actor Cleaner as C
actor Economy as E

rectangle "Purchasing an item" {
    (Purchase Item)   as pi
    (Check Balance)   as cb
}

C --> pi
pi --> E
pi .left.> cb : <<include>>
C -- cb
}
@enduml