@startuml
title Add vehicle to crossing
participant "roadNetwork :RoadNetwork" as rn
participant "crossing :Crossing" as cr
participant "vehicle :Vehicle" as vehicle

rn->cr: AddVehicle(vehicle:Vehicle)

cr -> vehicle: SetCrossing(crossing:Crossing)
vehicle -->cr 

cr-->rn
@enduml