@startuml
skinparam maxMessageSize 150

participant "timer: Timer" as timer
participant "a: Auto" as a
participant "l: Lane" as l
participant "r: Road" as r

title Auto elakadasa mely hoban

timer ->> a : <<event>> \n tick()



a -> a : checkSurfaceCondition()
activate a

a -> l : getSurfaceCondition()
activate a
l --> a : surfaceCondition: getSurfaceCondition
deactivate a

a -> a : setState(STUCK)
a -> l : setPassable(false)
l --> a

deactivate a
@enduml