@startuml
skinparam maxMessageSize 150

participant "timer: Timer" as timer
participant "a: Auto" as a
participant "l1: Lane (current)" as l1
participant "r2: Road (next)" as r2
participant "l2: Lane (next)" as l2
participant "rn: RoadNetwork" as rn
participant "c: Crossing (end)" as c

title Auto move() függvénye vegpont eleresekor

timer ->> a : <<event>> \n tick()
activate a

a -> a : move()

alt end of the road reached
    a -> l1 : removeVehicle(a: Vehicle)
    activate a
    l1 --> a

    a -> c : addVehicle(a: Vehicle)
    c --> a

    a -> rn : getNextRoad()
    rn --> a : nextRoad

    alt van jarhato ut

        a -> r2 : getLanes()
        r2 --> a : lanes: List<Lane>

    
        a -> a : chooseLane()
        
        a -> l2 : addVehicle(a: Vehicle)
        l2 -> a : setLane(l2: Lane)
        activate a
        a --> l2
        deactivate a
        l2 --> a
    end
    
    deactivate a
end

deactivate a
@enduml