@startuml
skinparam maxMessageSize 150
participant "b: Blower" as b
participant "sc: SurfaceCondition" as sc

activate b
b -> sc : setSnow(0)
deactivate b

activate sc
sc --> b
deactivate sc

activate b
b -> sc : setBrokenIce(0)
deactivate b

activate sc
sc --> b
deactivate sc

@enduml