@startuml
skinparam maxMessageSize 150
title Bus-auto crash

participant "timer: Timer" as timer
participant "b: Bus" as b
participant "l: Lane (jeges)" as l
participant "sc: SurfaceCondition" as sc
participant "a: Auto" as a

timer -> b : <<event>> tick()

activate b
b -> l : addVehicle(b)
deactivate b

activate l

l -> sc : hasIce()
activate sc
sc --> l : true
deactivate sc

l -> b : setState(SLIDE)
activate b
b -> l : handleTraffic()
deactivate b

l -> l : isPassable = false
l -> a : setState(CRASHED)
activate a
a --> l
deactivate a

l -> b : setState(WAIT)

deactivate l

@enduml
