@startuml
skinparam maxMessageSize 150
title Bus bus crash cleanup

participant "timer: Timer" as timer
participant "b1: Bus1" as b1
participant "l: Lane (jeges)" as l
participant "b2: Bus2" as b2


timer -> b1 : <<event>> tick()

activate b1
b1 -> b1 : decreaseWaitTicks--

alt b1.waitTicks == 0
    b1 -> l : handleTraffic()
    deactivate b1

    activate l
    l -> b1 : setState(NORMAL)
    deactivate l

    activate b1
    b1 --> l
    deactivate b1

    activate l
    l -> b2 : setWaitTicks(l.getRoadLength - b1.lanePosition)
    deactivate l

    activate b2
    b2 --> l
    deactivate b2

    activate l
    l --> b1
    deactivate l
end

@enduml