@startuml buyNewSnowPlow
skinparam maxMessageSize 150
title buyNewSnowPlow

actor "c: Cleaner" as c
participant "e: Economy" as e
participant "s: SnowPlower" as s

activate c
c -> e : buyNewSnowPlow()
deactivate c

activate e
e -> c : getMoney()
deactivate e

activate c
c --> e : return money
deactivate c

activate e
alt enough money
    e -> c : decreaseMoney(amount)
    activate c
    c --> e
    deactivate c

    e -> s ** : <<create>> new SnowPlower()
    s --> e : return SnowPlower

    e --> c : return SnowPlower
else not enough money
    e --> c : return null
end

deactivate e
@enduml
