@startuml
skinparam maxMessageSize 150
title Choosing the lane in a crossing
participant "bd: BudDriver" as bd
participant "cr: Crossing" as cr
participant "r: Road" as r
participant "l: Lane" as l

activate bd
bd -> cr : getRoads() 
activate cr
cr --> bd : List<Road> roads
deactivate cr

bd -> r : getLanes(Crossing cr)

activate r
r --> bd : List<Lane> lanes
deactivate r

bd -> l : addVehicle(Bus b)

activate l
l -> bd : setLane(Lane l)


activate bd
bd --> l
deactivate bd
l --> bd
deactivate l

deactivate bd
@enduml