@startuml
skinparam maxMessageSize 150
title Choosing the lane in a crossing
participant "c: Car" as bd
participant "l: Lane" as l

activate bd

bd -> l : addVehicle(Bus b)
activate l
alt
    l -> bd : setState(STUCK)
    activate bd
    bd --> l
    deactivate bd
else
    l -> bd : setState(SLIDE)
    activate bd
    bd --> l
    deactivate bd
end

activate l
l -> bd : setLane(Lane l)

activate bd
bd --> l
deactivate bd
l --> bd
deactivate l

deactivate bd
@enduml