@startuml
title Initialize cleaners
participant "director :GameDirector" as gd
participant "cleaner :Cleaner" as cleaner
participant "snowPlower :SnowPlower" as snowPlower
participant "head :Head" as head
    gd -> cleaner ** : <<create>> Cleaner(ht:HeadType)
    activate cleaner
    cleaner ->snowPlower  ** : <<create>> SnowPlower(ht: HeadType)

    snowPlower ->head**:<<create>> HeadType()
    head --> snowPlower: Head
    snowPlower -->cleaner: snowPlower
    cleaner-->gd: Cleaner
    deactivate cleaner
@enduml