@startuml processItem
skinparam maxMessageSize 150
skinparam sequenceMessageAlign center
title processItem

actor "c: Cleaner" as c
participant "e: Economy" as e

c -> e : processPurchase(SnowPlower s, ItemType item, int count)
activate e

e -> c : getMoney()
activate c
c --> e : return money
deactivate c

alt 
    e -> c : setMoney(money - prices[item] × count)
    activate c
    c --> e
    deactivate c
    e --> c : return true
else 
    e --> c : return false
end

deactivate e
@enduml
