@startuml
skinparam maxMessageSize 150
title road cleaning

participant "sp: SnowPlower" as sp
participant "l: Lane (jeges)" as l
participant "h: Head" as h

sp -> l : clean(currentHead)
activate l
l -> h : applyEffect(l)
deactivate l

activate h
h --> l
deactivate h

activate l
l --> sp
deactivate l


@enduml
