@startuml
skinparam maxMessageSize 150

participant "s: SaltSpreader" as s
participant "sc: SurfaceCondition" as sc

alt isSalted
    s -> sc : setIsSalted(true)
    activate sc
    sc --> s
    deactivate sc
end
@enduml